name: Publish Packages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup git user
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "Github"
